apiVersion : apps/v1
kind: Deployment
metadata:
  name: rilopespipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rilopespipelinesjavascriptdocker 
    spec:
      containers:
        - name: rilopespipelinesjavascriptdocker 
          image: acrlopes.azurecr.io/rilopespipelinesjavascriptdocker
          ports:
          - containerPort: 8080
